-- VHDL module instantiation generated by SCUBA Diamond_2.2_Production (99)
-- Module  Version: 1.1
-- Tue Dec  3 22:51:35 2013

-- parameterized module component declaration
component efbx
    port (wb_clk_i: in  std_logic; wb_rst_i: in  std_logic; 
        wb_cyc_i: in  std_logic; wb_stb_i: in  std_logic; 
        wb_we_i: in  std_logic; 
        wb_adr_i: in  std_logic_vector(7 downto 0); 
        wb_dat_i: in  std_logic_vector(7 downto 0); 
        wb_dat_o: out  std_logic_vector(7 downto 0); 
        wb_ack_o: out  std_logic; i2c1_scl: inout  std_logic; 
        i2c1_sda: inout  std_logic; i2c1_irqo: out  std_logic; 
        i2c2_scl: inout  std_logic; i2c2_sda: inout  std_logic; 
        i2c2_irqo: out  std_logic; spi_clk: inout  std_logic; 
        spi_miso: inout  std_logic; spi_mosi: inout  std_logic; 
        spi_scsn: in  std_logic; spi_irq: out  std_logic; 
        tc_clki: in  std_logic; tc_rstn: in  std_logic; 
        tc_ic: in  std_logic; tc_int: out  std_logic; 
        tc_oc: out  std_logic; 
        pll0_bus_i: in  std_logic_vector(8 downto 0); 
        pll0_bus_o: out  std_logic_vector(16 downto 0); 
        pll1_bus_i: in  std_logic_vector(8 downto 0); 
        pll1_bus_o: out  std_logic_vector(16 downto 0); 
        ufm_sn: in  std_logic; wbc_ufm_irq: out  std_logic; 
        cfg_wake: out  std_logic; cfg_stdby: out  std_logic);
end component;

-- parameterized module component instance
__ : efbx
    port map (wb_clk_i=>__, wb_rst_i=>__, wb_cyc_i=>__, wb_stb_i=>__, 
        wb_we_i=>__, wb_adr_i(7 downto 0)=>__, wb_dat_i(7 downto 0)=>__, 
        wb_dat_o(7 downto 0)=>__, wb_ack_o=>__, i2c1_scl=>__, i2c1_sda=>__, 
        i2c1_irqo=>__, i2c2_scl=>__, i2c2_sda=>__, i2c2_irqo=>__, 
        spi_clk=>__, spi_miso=>__, spi_mosi=>__, spi_scsn=>__, spi_irq=>__, 
        tc_clki=>__, tc_rstn=>__, tc_ic=>__, tc_int=>__, tc_oc=>__, 
        pll0_bus_i(8 downto 0)=>__, pll0_bus_o(16 downto 0)=>__, 
        pll1_bus_i(8 downto 0)=>__, pll1_bus_o(16 downto 0)=>__, ufm_sn=>__, 
        wbc_ufm_irq=>__, cfg_wake=>__, cfg_stdby=>__);
